AllCops:
  Exclude:
    - 'server/config/puma.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'config/db/schema.rb'
    - 'spec/int/db/schema.rb'
    - 'config/db/database.rake'
    - 'server/presentation/view/node_modules/**/*'

# Offenses count: 1. YAML.safe_load won't work with files using aliases
Security/YAMLLoad:
  Exclude:
    - 'server/infrastructure/database/model/entity.rb'

Metrics/LineLength:
  Max: 120
